'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

process.env.XDG_CACHE_HOME = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-to-html-render-'));

const { render, MAX_MARKDOWN_BYTES } = require('../bin/render');

test('render: skip on empty markdown', async () => {
  const r = await render({ markdown: '', sessionId: 'test', turnIndex: 0 });
  assert.equal(r.skipped, true);
});

test('render: skip on trivial reply', async () => {
  const r = await render({ markdown: 'HTML mode: ON', sessionId: 'test', turnIndex: 1 });
  assert.equal(r.skipped, true);
  assert.equal(r.reason, 'trivial');
});

test('render: prose for substantive paragraph', async () => {
  const md = '# Title\n\n' + 'a '.repeat(300);
  const r = await render({ markdown: md, sessionId: 'test', turnIndex: 2, autoOpen: false });
  assert.equal(r.skipped, false);
  assert.equal(r.template, 'prose');
  assert.ok(fs.existsSync(r.path));
  const html = fs.readFileSync(r.path, 'utf8');
  assert.ok(html.startsWith('<!doctype html>'));
  assert.ok(html.includes('</html>'));
  assert.ok(!/CSP locks/.test(html));
  assert.ok(!/Generated by cc-to-html/.test(html));
});

test('render: comparison template detected and rendered', async () => {
  const md = '# Pick\n\n## Option A\n\nPros\n- a\n\nCons\n- b\n\n## Option B\n\nPros\n- c';
  const r = await render({ markdown: md, sessionId: 'test', turnIndex: 3, autoOpen: false });
  assert.equal(r.template, 'comparison');
  const html = fs.readFileSync(r.path, 'utf8');
  assert.ok(html.includes('class="opt"'));
});

test('render: plan template detected and rendered', async () => {
  const md = '# Plan\n\n## Phase 1: A\n\n- [ ] one\n- [ ] two\n\n## Phase 2: B\n\n- [ ] three';
  const r = await render({ markdown: md, sessionId: 'test', turnIndex: 4, autoOpen: false });
  assert.equal(r.template, 'plan');
  const html = fs.readFileSync(r.path, 'utf8');
  assert.ok(html.includes('class="task '));
});

test('render: turnIndex is clamped on invalid input', async () => {
  const r = await render({ markdown: '# Hi\n\n' + 'x '.repeat(300), sessionId: 'test', turnIndex: '../evil' });
  assert.equal(r.turnIndex, 0);
});

test('render: sessionId with traversal is sanitized', async () => {
  const r = await render({ markdown: '# Hi\n\n' + 'x '.repeat(300), sessionId: '../../../tmp/evil', turnIndex: 5 });
  assert.ok(!r.path.includes('../'));
  assert.ok(r.sessionId.startsWith('s-'));
});

test('render: markdown over cap is truncated, not crashed', async () => {
  const big = '# T\n\n' + 'a '.repeat(MAX_MARKDOWN_BYTES);
  const r = await render({ markdown: big, sessionId: 'test', turnIndex: 6, autoOpen: false });
  assert.equal(r.ok, true);
  assert.ok(fs.existsSync(r.path));
});

test('render: HTML escapes script tags in title and body', async () => {
  const md = '# <script>alert(1)</script>\n\n' + 'a '.repeat(300);
  const r = await render({ markdown: md, sessionId: 'test', turnIndex: 7, autoOpen: false });
  const html = fs.readFileSync(r.path, 'utf8');
  assert.ok(!html.includes('<script>alert'));
});

test('render: override block forces template', async () => {
  const md = '```to-html\n{"template":"comparison","title":"Forced"}\n```\n\n## Option A\n\nPros\n- one\n\n## Option B\n\nPros\n- two';
  const r = await render({ markdown: md, sessionId: 'test', turnIndex: 8, autoOpen: false });
  assert.equal(r.template, 'comparison');
});

test('render: unknown override template falls back', async () => {
  const md = '```to-html\n{"template":"evil"}\n```\n\n# Topic\n\n' + 'a '.repeat(300);
  const r = await render({ markdown: md, sessionId: 'test', turnIndex: 9, autoOpen: false });
  assert.notEqual(r.template, 'evil');
});
